# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMovie
	pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON’
	pod "youtube-ios-player-helper", "~> 0.1.4"

  target 'iMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iMovieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
